# tls-scan - CI Build
# https://github.com/ArtiomL/tls-scan
# Artiom Lichtenstein
# v1.1.0, 06/11/2018

sudo: required

env:
  global:
  - REPO="artioml/tls-scan"

language: python
python:
  - "3.6"

services:
  - docker

before_install:
  - pip3 install --upgrade pip

install:
  - pip3 install -r requirements.txt

script:
  - ./tls_scan.py -c artioml.net
  - docker build -t $REPO .
  - docker images
  - docker run --rm $REPO ./tls_scan.py -c artioml.net

notifications:
  slack:
    secure: "Sc4xEaLjO2ieluiEd0AQ8/HhGsz7TLQcRnnv8HQUn18UgAb368shZfBkWQi65efknJ9WUvzXQnJOo4uaV14E8WNydFaLYe2gR7/remwyipMyqfz/+HcGO/hjkhqP2v5wbm8B+6a4Xwymb9UPmIl3qdlAYy9Oa8TSNOUPQm8ka4DEo54ESTUldOGvNZhGecLvsj/5DaHCgscXK8RZAfh/TfT6AvSaT5W73qGHcgIVSS/oreelDrtkzzCyXMPsdeZ5/Ia+uQdTdP1Ab2qxUYxlv6zdHCUvVl77vQxJIUDrT0OTLG82DK0Xm9Hol1wtG8uvPcTHUaFJ8DgljHulEnVEUbeaifapEb9INiXVqZjmB0IQ0x75ZrgwEb54YmdpNznkvw6d4OQuBAAkbODI7570hnAEoh/hFjvOhrm9NhN2baHL7IZfreiAsredTE3C4QwN2YwMDKnRGAeX8SJ7IlYGf64wKEwxrKm4iTXJKPUP+9F5mPI7cIdbq/SCfLjfd0TlIeZyrjq2gbut8Xo4b7iW5k9g6iqFDCAYL38G05/ZZcNFICWwjvjFxioUQruRxI/KgOHNhMjG2jbUDoEG5ypnxKARunOoIr7UoyTyJDdmefepdsfmaHHyBn4gUt63uA9WpjaByK72BPzonfGoZKCrOVfZ2/63xLirG+2hQVAyBDY="
